# Generated by Django 5.0.4 on 2024-04-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('animal_id', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
                ('species', models.CharField(max_length=100)),
                ('strain', models.CharField(max_length=100)),
                ('wean_date', models.DateField(blank=True, null=True)),
                ('euthanasia_date', models.DateField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=100)),
                ('use', models.CharField(choices=[('E', 'Experimental'), ('B', 'Breeder'), ('U', 'Undefined')], max_length=1)),
                ('room', models.CharField(max_length=100)),
                ('cage', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('female_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_of_female', to='colonyDB.animal')),
                ('male_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_of_male', to='colonyDB.animal')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colonyDB.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('animal_snapshot', models.JSONField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonyDB.animal')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentalGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonyDB.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='experimental_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colonyDB.experimentalgroup'),
        ),
    ]
